language: csharp

dotnet: 2.2
sudo: false

env:
  global:
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

script:
  - dotnet build Sekougi.MessagePack.sln -c Release
  - dotnet test -c Release --no-build Src/Sekougi.MessagePack.Tests/Sekougi.MessagePack.Tests.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_script:
  - bash <(curl -s https://codecov.io/bash)